### ISSUE TITLE
WMF Z format description

### ISSUE THREAD

**Issue by jyviko** [michal-szkutnik/pyRigolWfm1000Z#1]
Hi Michal,
Thank you for your contribution. Your piece is working nicely. I have contacted Rigol and they have sent me the file's format description. You can me email at jyviko at gmail dot com.  Maybe you can find it useful to retrieve more stuff from the file, although there are pieces that are undocumented. 

Cheers, 
Iraklis

**Comment by JBR48** [comment]
Hello,
I tried to use this program on WFM files I got from my MSO1104Z, but without any success. Two examples:
_ File "Z:\Electronics\Rigol\python\pyRigolWfm1000Z-master\wfm.py", line 91, in decodeNullTerminatedStr
    return string.decode('ascii').partition('\x00')[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x84 in position 0: ordinal not in range(128)

  File "Z:\Electronics\Rigol\python\pyRigolWfm1000Z-master\wfm.py", line 215, in parseRigolWFM
    sampleData.fromfile(f, nBytes)
EOFError: read() didn't return enough bytes_

Can you give a hint as to where I should look in the code to fix this? Alternatively, are you interested in the example files?

PS: my firmware revision is: 00.04.03.SP2
Greetings,
Jan

**Comment by jyviko** [comment]
Hi Jan,

Can you try 'ISO-8859-1' instead of 'ascii'? 

Best,
Iraklis

**Comment by JBR48** [comment]
Hello Iraklis,

I changed 'ascii' in wfm.py line 91 to 'ISO-8859-1'. Is this what you meant?
After doing this I get the same error for all three files. I have included one example file ScopeFile1.wfm (remove last .txt) with the corresponding ScopeFile1.txt file.

Z:\Electronics\Rigol\python>python3 wfmutil.py info --forgiving ScopeFile1.wfm
Traceback (most recent call last):
  File "wfmutil.py", line 270, in <module>
    scopeData = wfm.parseRigolWFM(f, args.forgiving)
  File "Z:\Electronics\Rigol\python\wfm.py", line 215, in parseRigolWFM
    sampleData.fromfile(f, nBytes)

EOFError: read() didn't return enough bytes

Z:\Electronics\Rigol\python>python3 wfmutil.py info --forgiving TestFile1.wfm
Traceback (most recent call last):
  File "wfmutil.py", line 270, in <module>
    scopeData = wfm.parseRigolWFM(f, args.forgiving)
  File "Z:\Electronics\Rigol\python\wfm.py", line 215, in parseRigolWFM
    sampleData.fromfile(f, nBytes)
EOFError: read() didn't return enough bytes

Z:\Electronics\Rigol\python>python3 wfmutil.py info --forgiving TestFile2.wfm
Traceback (most recent call last):
  File "wfmutil.py", line 270, in <module>
    scopeData = wfm.parseRigolWFM(f, args.forgiving)
  File "Z:\Electronics\Rigol\python\wfm.py", line 215, in parseRigolWFM
    sampleData.fromfile(f, nBytes)
EOFError: read() didn't return enough bytes

[ScopeFile1.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/229002/ScopeFile1.txt)
[ScopeFile1.wfm.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/229004/ScopeFile1.wfm.txt)

**Comment by michal-szkutnik** [comment]
Hi,
Probably the file format is different, I will take a look at the file you supplied this or next week and see if this is some minor change or something bigger and if I can deal with it.

**Comment by michal-szkutnik** [comment]
Hi,
Some offsets were changed in the new firmware version. I will provide a fix in a few days.

**Comment by JBR48** [comment]
Dear Michal,
Thank you very much for your efforts.

**Comment by michal-szkutnik** [comment]
I updated the repo with support for new firmware version. Check it out.

**Comment by JBR48** [comment]
I tested the new version and worked on all examples that I had collected until now.
Thank you, this will be very useful to me!
