### ISSUE TITLE
New firmware 00.04.04.SP3 support 

### ISSUE THREAD

**Issue by ro-bercik** [michal-szkutnik/pyRigolWfm1000Z#4]
Hi Michal,
great work, first of all. I have two oscilloscopes: DS1074Z and DS1074Z-Plus. Actual version of script works only partialy on their firmware.

When I load 001x.wfm I receive this:
```
Traceback (most recent call last):
  File "./wfmutil.py", line 269, in <module>
    scopeData = wfm.parseRigolWFM(f, args.forgiving)
  File "/root/wfm.py", line 200, in parseRigolWFM
    fileHdr = _parseFile(f, wfm_header, strict=strict)
  File "/root/wfm.py", line 63, in _parseFile
    data[field] = _parseFile(f, test, leading)
  File "/root/wfm.py", line 73, in _parseFile
    data[field] = transform(data[field])
  File "/root/wfm.py", line 91, in decodeNullTerminatedStr
    return string.decode('ascii').partition('\x00')[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 0: ordinal not in range(128)
```
Ofcourse when I change 'ascii' in line 91 of wfm.py to 'ISO-8859-1' I receive:
```
General
=======
Device model             : DS1074Z
Firmware version         : 00.04.04.SP3
Horizontal scale         : 2000000000 ps
Time delay               : 10000000000 ps
Sampling rate            : 1.250000e+08 samples/s
Enabled channels         : [0, 1, 2] (zero-based indexes)

Channel CH1
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 5.000e-02 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 1.000e-02 s
No. of recorded samples  : 0

Channel CH2
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 5.000e-01 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 1.000e-02 s
No. of recorded samples  : 0

Channel CH3
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 2.000e-01 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 1.000e-02 s
No. of recorded samples  : 0

Channel CH4
===========
Label                    : ³64
Enabled                  : False

  plik 004y.wfm -> DS1074Z-PLUS -> ascii
                                -> ISO-8859-1

General
=======
Device model             : DS1074Z Plus
Firmware version         : 00.04.04.SP3
Horizontal scale         : 5000000 ps
Time delay               : 9000000000 ps
Sampling rate            : 1.250000e+08 samples/s
Enabled channels         : [0, 1, 2] (zero-based indexes)

Channel CH1
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 1.000e-03 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 9.000e-03 s
No. of recorded samples  : 0

Channel CH2
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 1.000e-03 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 9.000e-03 s
No. of recorded samples  : 0

Channel CH3
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 1.000e-03 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 9.000e-03 s
No. of recorded samples  : 0

Channel CH4
===========
Label                    :
Enabled                  : False
```
On file 004y.wfm in both cases (ascii and ISO) i receive this:
```
General
=======
Device model             : DS1074Z Plus
Firmware version         : 00.04.04.SP3
Horizontal scale         : 5000000 ps
Time delay               : 9000000000 ps
Sampling rate            : 1.250000e+08 samples/s
Enabled channels         : [0, 1, 2] (zero-based indexes)

Channel CH1
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 1.000e-03 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 9.000e-03 s
No. of recorded samples  : 0

Channel CH2
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 1.000e-03 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 9.000e-03 s
No. of recorded samples  : 0

Channel CH3
===========
Label                    :
Enabled                  : True
Probe attenuation        : 0.000x
Y grid scale             : 1.000e-03 V/div
Y shift                  : 0.000e+00 V
Y inverted               : False
Sampling rate            : 1.250e+08 samples/s
Time delay               : 9.000e-03 s
No. of recorded samples  : 0

Channel CH4
===========
Label                    :
Enabled                  : False
```
I will be glad to you, if you could check this files.

Here are txt files with osc config:
[001x.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/2396366/001x.txt)
[004y.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/2396367/004y.txt)
Images of signals:
![001x](https://user-images.githubusercontent.com/43404500/45744052-0b897080-bbed-11e8-8d96-d46fd7e4c9c7.png)
![004y](https://user-images.githubusercontent.com/43404500/45744062-104e2480-bbed-11e8-936d-b009f3886bb6.png)
Wfm files:
[001x.wfm.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/2396374/001x.wfm.txt)
[004y.wfm.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/2396381/004y.wfm.txt)
and csv files:
[001x.csv.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/2396393/001x.csv.txt)
[004y.csv.txt](https://github.com/michal-szkutnik/pyRigolWfm1000Z/files/2396406/004y.csv.txt)

**Comment by scottprahl** [comment]
Look at https://github.com/scottprahl/RigolWFM for support for the Rigol 4000 .wfm files.  Specifically, look at https://github.com/scottprahl/RigolWFM/blob/master/doc/1-DS4000-Waveforms.ipynb where your files (thanks!) were analyzed.

**Comment by ro-bercik** [comment]
It's nice to see that this data has helped :). When the known situation calms down, I will try to dump more data with newer firmware of this oscilloscope.
